import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./custom-component/SideBar";
import { AuthProvider } from "./custom-component/global/AuthProfider";
import { RouteGuard } from "./custom-component/global/RouteGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F8F8F8] flex flex-col md:flex-row h-screen overflow-hidden`}>
        <AuthProvider>
          {/* Sidebar handles its own width responsiveness now */}
          <SideBar />

          {/* Content Area — protected by RouteGuard */}
          <div className="w-full flex-1 overflow-auto">
            <RouteGuard>
              {children}
            </RouteGuard>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
